### ISSUE TITLE
iOS datepicker results in invalid format

### ISSUE THREAD

**Issue by ARBaart** [dwh-outsite/bar-bookings#10]
When I try to create an event the dates trigger the datepicker keyboard. Not an issue except the resulting format seems to be invalid. Since I can’t type it in the correct ISO format because the datepicker replaces the regular keyboard, this makes it impossible to create an new event on mobile. 

![3F00B80D-B3ED-4664-953C-01105DCFFC67](https://user-images.githubusercontent.com/643200/91655366-54702200-eab0-11ea-8806-3df9425c61f7.jpeg)

**Comment by casperboone** [comment]
Apparently, this was an iOS issue. It’s working in iOS 14 :)
