### ISSUE TITLE
Optional confirmation email text is not very optional

### ISSUE THREAD

**Issue by ARBaart** [dwh-outsite/bar-bookings#28]
If left empty-ish (empty or space) you cannot submit

**Comment by casperboone** [comment]
Fixed!

**Comment by ARBaart** [comment]
Does not seem fixed
<img width="342" alt="Screenshot 2021-07-14 at 11 19 56" src="https://user-images.githubusercontent.com/643200/125597539-64ea5c19-cde6-4aaf-ac39-8cf9189c7962.png">

**Comment by casperboone** [comment]
Fixed :)

_technically the issue was actually fixed and this is a different issue but that's ok ;)_
